version: '3'
services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/Neo4j
    volumes:
      - data:/data
      - logs:/logs
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo-db
    command: sh start.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_USERNAME=neo4j
      - DATABASE_PASSWORD=Neo4j
      - DATABASE_HOST=bolt://neo-db:7687
      - API_KEY=qxf2
      - PROJECT_NAME=Help Survey Project
      - ADMIN_EMAIL=["akkul.dn@qxf2.com"]
      - GRAPHQl_USERNAME=dummy
      - GRAPHQL_PASSWORD=dummy
      - URL=http://localhost:8000/

volumes:
  data:
  logs:
