version: '3'
services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${DATABASE_USERNAME}/${DATABASE_PASSWORD}
    volumes:
      - data:/data
      - logs:/logs
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo-db
    entrypoint: ["sh", "-c", "wait-for-it -t 180 -s bolt://neo-db:7687  -- echo 'Neo4j database is up' && (nohup uvicorn main:app --host 0.0.0.0 --reload &) && sleep 5 && cd /code/backend/db_backup_and_restore && python neo4j_restore.py && sleep 5 && cd /code/virtualized_employees_graphql_server && rm -rf ./node_modules && ln -s /code/mock_server_node_packages/node_modules/ . && (nohup node mock-graphql-server.js &) && cd /code/frontend && rm -rf ./node_modules && ln -s /code/react_node_packages/node_modules/ . && npm start"]
    ports:
      - "8000:8000"
      - "3000:3000/tcp"
      - "5000:5000"
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=bolt://neo-db:7687
      - API_KEY=${API_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - GRAPHQL_BASE_URL=${GRAPHQL_BASE_URL}
      - GRAPHQl_USERNAME=${GRAPHQl_USERNAME}
      - GRAPHQL_PASSWORD=${GRAPHQL_PASSWORD}
      - URL=${URL}
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/code/backend
      - ./frontend/public:/code/frontend/public
      - ./frontend/src:/code/frontend/src
      - ./frontend/package.json:/code/frontend/package.json
      - ./virtualized_employees_graphql_server/mock-graphql-server.js:/code/virtualized_employees_graphql_server/mock-graphql-server.js
      - ./virtualized_employees_graphql_server/employee-data.json:/code/virtualized_employees_graphql_server/employee-data.json
      - ./virtualized_employees_graphql_server/package.json:/code/virtualized_employees_graphql_server/package.json
volumes:
  data:
  logs: