version: '3'
services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/Neo4j
    volumes:
      - data:/data
      - logs:/logs
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 &
    ports:
      - "8000:8000"
    environment:
      - DATABASE_USERNAME=neo4j
      - DATABASE_PASSWORD=Neo4j
      - DATABASE_HOST=bolt://localhost:7687
      - API_KEY=qxf2
      - PROJECT_NAME=Help Survey Project
      - CLIENT_ID=361336870916-q88h5gho5ee7p1mudg32je26th6pjlv5.apps.googleusercontent.com
      - ADMIN_EMAIL=["akkul.dn@qxf2.com"]
      - GRAPHQl_USERNAME=dummy
      - GRAPHQL_PASSWORD=dummy
      - URL=http://localhost:8000/
    depends_on:
      - neo-db
volumes:
  data:
  logs:
