version: '3'
services:
  neo-db:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${DATABASE_USERNAME}/${DATABASE_PASSWORD}
    volumes:
      - data:/data
      - logs:/logs
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo-db
    command: sh start.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=bolt://neo-db:7687
      - API_KEY=${API_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - GRAPHQl_USERNAME=dummy
      - GRAPHQL_PASSWORD=dummy
      - URL=${URL}

volumes:
  data:
  logs:
